# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Versions
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.x.x
          8.x.x
          7.x.x
          6.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Sharphook
      run: dotnet build Sharphook --no-restore
    - name: Test Sharphook
      run: dotnet test Sharphook --no-build --verbosity normal
